#!/bin/bash
#client file
DATA_FILE="data.txt"

read -p "Enter your account ID: " ID
while true; do
# Check if ID exists
if ! grep -q "^$ID|" "$DATA_FILE"; then
    echo ""
    echo "#####################################"
    echo "Account not found!"
    echo "#####################################"
    exit 1
fi

#operations menu
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "-> 1) Withdraw"
echo "-> 2) Deposit"
echo "-> 3) Show Balance"
echo "-> 4) Cancel"
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"

read -p "Choose an option: " option

#switch between operations
case $option in
    1) 
        read -p "Enter amount to withdraw: " amount
        balance=$(grep "^$ID|" "$DATA_FILE" | cut -d'|' -f3)
        if (( amount > balance )); then
            echo "-----------------------------------------"
            echo "Insufficient balance!"
            echo "-----------------------------------------"
        else
            new_balance=$((balance - amount))
            sed -i "s/^$ID|.*|.*/$ID|$(grep "^$ID|" "$DATA_FILE" | cut -d'|' -f2)|$new_balance/" "$DATA_FILE"
            echo "-----------------------------------------"
            echo "Withdrawal successful. New balance: $new_balance"
            echo "-----------------------------------------"
        fi
        ;;
    2) 
        read -p "Enter amount to deposit: " amount
        balance=$(grep "^$ID|" "$DATA_FILE" | cut -d'|' -f3)
        new_balance=$((balance + amount))
        sed -i "s/^$ID|.*|.*/$ID|$(grep "^$ID|" "$DATA_FILE" | cut -d'|' -f2)|$new_balance/" "$DATA_FILE"
        echo "-----------------------------------------"
        echo "Deposit successful. New balance: $new_balance"
        echo "-----------------------------------------"
        ;;
    3) 
        balance=$(grep "^$ID|" "$DATA_FILE" | cut -d'|' -f3)
        echo "Your balance: $balance"
        ;;
    4) 
        echo "-----------------------------------------"
        echo "Operation cancelled "
        echo "Thank you for using our services!"
        echo "-----------------------------------------"
        exit 0
        ;;
    *) 
        echo "-----------------------------------------"
        echo "Invalid option!"
        echo "-----------------------------------------"
        ;;
esac
done